### ISSUE TITLE
push cargo.lock to repo

### ISSUE THREAD

**Issue by crocuda** [parazyd/arg#1]
Hi!  Could you please push the Cargo.lock file to the repo?

It is something needed for package manager that are a little bit to sensitives on versionning.

I need it to build the drakfi workspace.

In fact if you could do it for halo2_proofs, and halo2_gadget too, this would be great!

**Comment by parazyd** [comment]
This is a library, so Cargo.lock should not be a part of the repository.

**Comment by crocuda** [comment]
Fine!
